version: "3.9"

services:
  backend:
    image: ngoquangthang/travelmate-backend:latest
    container_name: travelmate-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=travelmate
    depends_on:
      - db

  frontend:
    image: ngoquangthang/travelmate-frontend:latest
    container_name: travelmate-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: travelmate-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=travelmate
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
