name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/travelmate-backend:latest ./travel-mate

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/travelmate-backend:latest

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/travelmate-frontend:latest ./travel-mate-fe

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/travelmate-frontend:latest
