name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Thiết lập Java để build backend
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build backend bằng Maven
      - name: Build backend
        run: mvn -B clean package -DskipTests -f travel-mate/pom.xml

      # Đăng nhập Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push backend image
      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/travelmate-backend:latest ./travel-mate
          docker push ${{ secrets.DOCKER_USERNAME }}/travelmate-backend:latest

      # Build & push frontend image
      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/travelmate-frontend:latest ./travel-mate-fe
          docker push ${{ secrets.DOCKER_USERNAME }}/travelmate-frontend:latest
